swagger: "2.0"
info:
  description: "API dt money"
  version: "1.0.0"
  title: "dt money API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "dtmoney.swagger.io"
basePath: "/v2"
tags:
  - name: "transaction"
    description: "Operations about Transaction"
    externalDocs:
      description: "Find out more about our store"
      url: "http://swagger.io"
schemes:
  - "https"
  - "http"
paths:
  /transactions:
    post:
      tags:
        - transaction
      summary: Cria uma transação
      description: Cria uma transação
      operationId: createTransaction
      produces:
        - application/json
      parameters:
        - name: input
          in: body
          description: Informações da transação
          required: true
          schema:
            $ref: "#/definitions/TransactionInputT"
      responses:
        '200':
          description: Operação realizada com sucesso
          schema:
            $ref: '#/definitions/TransactionResponse'
        '404':
          description: Erro ao tentar incluir uma transação
    get:
      tags:
        - transaction
      summary: Retorna todas as transações
      description: Retorna todas as transações
      operationId: getAllTransactions
      produces:
        - "application/json"
      responses:
        "200":
          description: successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/TransactionResponse"
        "404":
          description: Erro, não encontrado nenhuma transação
  /transactions/{id}:
    put:
      tags:
        - transaction
      summary: Atualiza a transação
      description: Atualiza a transação.
      operationId: updateTransaction
      produces:
        - "application/json"
      parameters:
        - name: id
          in: path
          description: Id da transação
          required: true
          type: integer
        - in: body
          name: body
          description: Atualizar transação com objeto.
          required: true
          schema:
            $ref: "#/definitions/TransactionInputT"
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/TransactionResponse"
        "400":
          description: Id da transação inválida ou não existe.
        "404":
          description: Transação não encontrada.
definitions:
  TransactionInputT:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      amount:
        type: string
      type:
        type: string
      category:
        type: string

  TransactionResponse:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      amount:
        type: number
        format: double
      type:
        type: string
      category:
        type: string

  BooleanResponse:
    type: boolean
    properties:
      saved:
        type: boolean

externalDocs:
  description: TBD
  url: 'http://TBD'