swagger: "2.0"
info:
  description: "API dt money"
  version: "1.0.0"
  title: "dt money API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "dtmoney.swagger.io"
basePath: "/v2"
tags:
  - name: "transaction"
    description: "Operations about Transaction"
    externalDocs:
      description: "Find out more about our store"
      url: "http://swagger.io"
schemes:
  - "https"
  - "http"
paths:
  /transactions:
    post:
      tags:
        - transaction
      summary: Cria uma transação
      description: Cria uma transação
      operationId: createTransaction
      produces:
        - application/json
      parameters:
        - name: input
          in: body
          description: Informações da transação
          required: true
          schema:
            $ref: "#/definitions/TransactionInputT"
      responses:
        '200':
          description: Operação realizada com sucesso
          schema:
            $ref: '#/definitions/TransactionResponse'
        '404':
          description: Erro ao tentar incluir uma transação
definitions:
  TransactionInputT:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      amount:
        type: string
      type:
        type: string
      category:
        type: string

  TransactionResponse:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      amount:
        type: number
        format: double
      type:
        type: string
      category:
        type: string

externalDocs:
  description: TBD
  url: 'http://TBD'